server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/bingeo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2

app:
  jwt:
    secret: "change-me-please-super-secret-64bytes"
    expiryDays: 7
